language: python
python:
  - "3.7"

env:
  - SERVER_IP_ADDRESS=207.180.208.87

before_install:
- openssl aes-256-cbc -K $encrypted_88abb8ca27c9_key -iv $encrypted_88abb8ca27c9_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@207.180.208.87 pwd

after_install:
  - python main.py