language: python

env:
  - SERVER_IP_ADDRESS=207.180.208.87

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - docker build -t veotani/travis-python-test:0.0 .

before_deploy:
  - openssl aes-256-cbc -K $encrypted_88abb8ca27c9_key -iv $encrypted_88abb8ca27c9_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@207.180.208.87 pwd

deploy:
  # Push image to dockerhub
  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    on:
      branch: master

  # Deploy on remote machine
  - provider: script
    skip_cleanup: true
    script: ssh -i ./deploy_key root@207.180.208.87 docker run -d -p 7000-8000:8080 veotani/travis-python-test:0.0
    on:
      branch: master

  